// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGky6A2clozzSLQBiVAlLNtkjNx5xcUl0',
    appId: '1:944421071442:web:849672dce8d66d534a8d8b',
    messagingSenderId: '944421071442',
    projectId: 'lunchify-d7150',
    authDomain: 'lunchify-d7150.firebaseapp.com',
    storageBucket: 'lunchify-d7150.firebasestorage.app',
    measurementId: 'G-RTZ6D1WW73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8VutWYFQbbRC4o5eVmEIucuKVrHl2xqM',
    appId: '1:944421071442:android:5fa2509233f3cb844a8d8b',
    messagingSenderId: '944421071442',
    projectId: 'lunchify-d7150',
    storageBucket: 'lunchify-d7150.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOPjzXANb29HVDZvyeVarOd_hOzakU6_Q',
    appId: '1:944421071442:ios:6e2d57c0f4abf30c4a8d8b',
    messagingSenderId: '944421071442',
    projectId: 'lunchify-d7150',
    storageBucket: 'lunchify-d7150.firebasestorage.app',
    iosBundleId: 'com.example.lunchify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOPjzXANb29HVDZvyeVarOd_hOzakU6_Q',
    appId: '1:944421071442:ios:6e2d57c0f4abf30c4a8d8b',
    messagingSenderId: '944421071442',
    projectId: 'lunchify-d7150',
    storageBucket: 'lunchify-d7150.firebasestorage.app',
    iosBundleId: 'com.example.lunchify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGky6A2clozzSLQBiVAlLNtkjNx5xcUl0',
    appId: '1:944421071442:web:5d9eb4fea5aa4d654a8d8b',
    messagingSenderId: '944421071442',
    projectId: 'lunchify-d7150',
    authDomain: 'lunchify-d7150.firebaseapp.com',
    storageBucket: 'lunchify-d7150.firebasestorage.app',
    measurementId: 'G-L2NPMCGMLW',
  );
}
